### ISSUE TITLE
Add this Forge 1.20.x port to WorldEditCUI

### ISSUE THREAD

**Issue by Tsoccerguy3** [EngineHub/WorldEditCUI#101]
### The Problem

Support Forge with this port
https://github.com/zbx1425/WorldEditCUI-Arch

### A Solution

add this Forge 1.20 code to this project
https://github.com/zbx1425/WorldEditCUI-Arch

### Alternatives

https://github.com/zbx1425/WorldEditCUI-Arch

### Anything Else?

https://github.com/zbx1425/WorldEditCUI-Arch

**Comment by zml2008** [comment]
That would be up to that fork maintainer to contribute, we will not copy it directly.

**Comment by Tsoccerguy3** [comment]
The Fork maintainer stated that it was a direct copy and the Forge method of Arch was used instead of Fabric to handle display . Its open source . There is mo issue to map to Forge .
