### ISSUE TITLE
Modrinth

### ISSUE THREAD

**Issue by Avakining** [EngineHub/WorldEditCUI#102]
### The Problem

I'm trying to use modrinth over curseforge whenever possible (as CF has a much worse privacy policy and is supporting genocide in Palestine), but WorldEditCUI isn't on modrinth yet.

### A Solution

In #38, modrinth support was listed as being "Will consider modrinth one day", and that was over two years ago.

### Anything Else?

Thanks you your time!

**Comment by zml2008** [comment]
Releases are available on GitHub releases, modrinth may happen at some point
