### ISSUE TITLE
1.18.2 release

### ISSUE THREAD

**Issue by C0dex73** [EngineHub/WorldEditCUI#106]
### The Problem

On github releases you do not support 1.18.2 and the 1.18.1 version is not compatible (for at least a certain version of fabric which is fully compatible with minecraft 1.18.2) due to a update on Fabric from fabric lifecycle events 1.x.x to 2.x.x

### A Solution

I searched through the commits of this git and found a version for 1.18.2 which is just the 1.18.1 version but with a [config file](https://github.com/EngineHub/WorldEditCUI/blame/9e06c54d943666f98dc9596dc2376bfce25b80e5/src/main/resources/fabric.mod.json) modified line 35 to adapt to the new version of fabric lifecycle events.
You could just rebuild the jar file with from this version of the source code and put it in 1.18.2 release.

### Alternatives

If this request will be ignored I put here a way for people to do it themselves (on windows) : 
First, download the [source code from 1.18.1 version](https://github.com/EngineHub/WorldEditCUI/archive/refs/tags/1.18.1+01.zip) and extract it from the archive.
Then, go into **src/main/ressources** and open the file named **fabric.mod.json** in a text editor like notepad.
Next, go to line 35 and modifiy `"fabric-lifecycle-events-v1": "^1.0.0",` to `"fabric-lifecycle-events-v1": "^2.0.0",`.
After that, return to the root of the extracted code (inside the **WorldEditCUI-1.18.1-01** folder) and type *cmd* inside the address bar (see screenshot) to open a command prompt with the cwd being this folder
![Capture](https://github.com/EngineHub/WorldEditCUI/assets/95096929/b2bd5480-55f6-4684-9a5d-1df75857beaa)
In this promp copy this command : `gradlew build`
Wait for the command to build the .jar file
When it is done, go into **build\libs** and the mod file is **WorldEditCUI-1.18.1+01.jar** (you can rename it to 1.18.2+01)

### Anything Else?

I know 1.18.2 is not the latest version of Minecraft but it is the most used for redstone servers as the 1.21 snapshots arn't that stable (and we are not gonna talk about that copper bulb).

**Comment by zml2008** [comment]
no
