### ISSUE TITLE
Toggelable overlay

### ISSUE THREAD

**Issue by enderkruemel** [EngineHub/WorldEditCUI#107]
### The Problem

it is currently not possible to switch the overlay off if not needet. 

### A Solution

add an button / keybind option to switch it on and off.

**Comment by Joo200** [comment]
There is a keybind, you can set it in the settings:
![grafik](https://github.com/EngineHub/WorldEditCUI/assets/15250323/2d6b1066-092c-4548-9cc0-d87a39ac99f7)

**Comment by enderkruemel** [comment]
as i use an older version (1.20.1) this option doesnt exist there...  or is there any build that has the button for 1.20.1?

**Comment by Joo200** [comment]
keybinds should be in the 1.20.1 version too. they are in the keybinds section, not in the settings of WorldEditCUI.

**Comment by enderkruemel** [comment]
ok? i removed the mod and reset my config files, now it is there ... wierd, but ok.
