### ISSUE TITLE
1.12.3/4 Release

### ISSUE THREAD

**Issue by Torphedo** [EngineHub/WorldEditCUI#126]
### The Problem

For some reason there's no updated 1.21.3 file on [Modrinth](https://modrinth.com/mod/worldedit-cui) or here.

### A Solution

The `mc/1.12.3` branch indicates it's ready for release, and when I built it myself it works perfectly on 1.21.4. Could you upload an updated JAR so other people don't need to build it from source?

**Comment by Joo200** [comment]
Duplikate of #125 and many others

**Comment by ShayBox** [comment]
You didn't explain why no release, just linked to a duplicate issue also with no explanation.  
"Duplikate" is not a very useful reason to close an issue unless you link to the duplicate that explains the reason...
