### ISSUE TITLE
1.18 Dev build crashing

### ISSUE THREAD

**Issue by TomLewis** [EngineHub/WorldEditCUI#55]
### WorldEditCUI Version

WorldEditCUI-1.16.5+03-SNAPSHOT.jar

### Fabric Version

0.12.12

### Fabric API Version

fabric-api-0.45.0+1.18.jar

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEditCUI compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.

### Bug Description

I'm using fabulously-optimized via MultiMC so its most likely the problem, using latest dev build for 1.18.1 and it crashes as soon as I load into game.
Crashlog with full stats https://crashy.net/VhsKNkew38J1uc7trnw8

The modpack (To replace optifine) 
https://www.curseforge.com/minecraft/modpacks/fabulously-optimized

The build I used:
https://github.com/EngineHub/WorldEditCUI/actions/runs/1619630616

### Expected Behavior

Not crash.

### Reproduction Steps

1. Install MultiMC  & fabulously-optimized
2. Install latest dev build for WECUI
3. Load a world/server

**Comment by TomLewis** [comment]
The title says "Update to 1.18.1" ...

**Comment by zml2008** [comment]
> WorldEditCUI Version
> 
> WorldEditCUI-1.16.5+03-SNAPSHOT.jar

**Comment by TomLewis** [comment]
The build name says 1.18.1 -> https://github.com/EngineHub/WorldEditCUI/actions/runs/1619630616

**Comment by wizjany** [comment]
https://i.imgur.com/6jsPT4s.png
