### ISSUE TITLE
Changing to GPLv3

### ISSUE THREAD

**Issue by octylFractal** [EngineHub/WorldEditCUI#56]
Hi everyone, as part of inclusion in EngineHub we'd like to re-license the project to GPL so that we can potentially link it with WorldEdit or a common library if needed. Unfortunately, that means that we need permission from all copyright holders to change the license to GPLv3, as EPLv1 is not compatible with the GPL.

So, if you're mentioned below, please comment stating your approval or disapproval for us to change to GPLv3.

- [x] @yetanotherx
- [ ] @Mumfrey
- [x] @zml2008 
- [x] @mikroskeem 
- [x] @StartForKillerMC
- [x] @james090500

All other contributors I didn't include, as it appears their changes have been erased by the sands of time, or weren't significant (<100 lines), or weren't code changes. Notably, lahwran's code no longer appears to be part of the current HEAD repository, so I don't think we need their permission to switch the license.

If we don't get all responses by 2023, or we get a negative reply, I'll likely abandon the idea of moving this to GPL, but that might mean that I work on <https://github.com/EngineHub/WorldEditVisualizer> instead, since that is GPL-able.

**Comment by zml2008** [comment]
I (zml2008) will gladly release all contributions I have made to WorldEditCUI under the terms of the GPL v3 or later.

**Comment by mikroskeem** [comment]
I (mikroskeem) will gladly release all contributions I have made to WorldEditCUI under the terms of the GPL v3 or later.Message ID: ***@***.***>

**Comment by StartForKillerMC** [comment]
Sure, i approve the change, there is no problem for me to change it to GPLv3

**Comment by james090500** [comment]
I approve

**Comment by StartForKillerMC** [comment]
@yetanotherx hasn't been active for a while as it seems

**Comment by octylFractal** [comment]
I've contacted them on Reddit as they're active as of yesterday there.

**Comment by yetanotherx** [comment]
While I generally personally prefer to use other non-GPL licenses for my open source work, I approve re-licensing my past contributions to this project, as I do not feel it is appropriate for me to block future improvements to a project that I have not been active on in many years.

**Comment by Toseflo** [comment]
Have you tried contacting Mumfrey on Discord yet? I don't know if he has his private messages open, but at least he is on the Paper Discord and from there you could contact him.
I didn't want to contact him myself, because I'm not

**Comment by octylFractal** [comment]
This unfortunately won't be able to happen, we've decided to just switch to EPLv2 for now #112 .
