### ISSUE TITLE
1.18.x release

### ISSUE THREAD

**Issue by H4ckerxx44** [EngineHub/WorldEditCUI#58]
### The Problem

It seems like this mod is compatible with `1.18.x` (#53 implies that imo) so I think an actual release with a mod would be helpful.

### A Solution

Create a release for `1.18.x`.

### Alternatives

Explain the current state of the `mc/1.18` branch.

**Comment by octylFractal** [comment]
> Explain the current state of the mc/1.18 branch.
It's experimental.

**Comment by H4ckerxx44** [comment]
Alright, thanks.
