### ISSUE TITLE
Toggle view on and off.

### ISSUE THREAD

**Issue by level42ca** [EngineHub/WorldEditCUI#72]
### The Problem

I'm not sure if this is already possible, and I just don't know how to do it, but if possible, I think it'd be nice to have this view togglable.

### A Solution

 For example, I'm trying to see what a certain colour block looks like in my build, but the lines are awfully distracting. It'd be nice to hide the grid for a moment, to see the blocks on their own. Just a though. Thanks for a great plugin none the less.

**Comment by wizjany** [comment]
exists already.

**Comment by zml2008** [comment]
look at the available key bindings
