### ISSUE TITLE
Can't see anything with big selection, and it's pretty hard to see anything in general

### ISSUE THREAD

**Issue by TheBlackEntity** [EngineHub/WorldEditCUI#76]
### WorldEditCUI Version

1.19+01

### Fabric Version

Quilt 0.17.4

### Fabric API Version

I have no idea...

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEditCUI compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.

### Bug Description

If you have a big selection, you pretty much can't see anything anymore.

And in general, it's very hard to see anything when having a selection.

![2022-10-15_20 07 33](https://user-images.githubusercontent.com/36412486/196001866-a9e94daf-bc2a-4b5e-abf6-f1ac9121b63e.png)
![2022-10-15_20 07 37](https://user-images.githubusercontent.com/36412486/196001871-c6964014-5624-4ca0-b37a-e14e3e9f5887.png)

### Expected Behavior

You should be able to see

### Reproduction Steps

1. Make a big selection
2. Try to see

**Comment by wizjany** [comment]
duplicates #24
