### ISSUE TITLE
Please change the version name from 1.19 to 1.19.2.

### ISSUE THREAD

**Issue by ipiiia** [EngineHub/WorldEditCUI#77]
### The Problem

It helps when using ferium (mods auto-updater)

### A Solution

change the version name from 1.19 to 1.19.2

**Comment by ipiiia** [comment]
> But... it isn't for 1.19.2 specifically, it was made against 1.19. Why should we name it something it isn't?

It works well on 1.19.2, so isn't it okay to change the version name?

**Comment by zml2008** [comment]
curseforge has a field for supported versions, if your updater isn't using that it's broken
