### ISSUE TITLE
Area display bug

### ISSUE THREAD

**Issue by khoor3** [EngineHub/WorldEditCUI#84]
### WorldEditCUI Version

1.19+01

### Fabric Version

Fabric 0.14.9

### Fabric API Version

Fabric API 0.62.0+1.19.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEditCUI compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.

### Bug Description

This mod not only shows the area of WorldEdit but also shows the area of Residence.

### Expected Behavior

A keybind to disable WECUI and a keybind to enable.

### Reproduction Steps

1.Join a server with residence plugin.
2.Select an area.
3.Disconnect and reconnect.

**Comment by zml2008** [comment]
This would be functionality offered by the Residence plugin, not something WECUI can toggle individually.
