### ISSUE TITLE
Add forge 1.19 builds of WorldEditCUI Mod

### ISSUE THREAD

**Issue by StealthyExpertX** [EngineHub/WorldEditCUI#89]
### The Problem

I would like support for WorldEditCUI so we can have forge builds and not just fabric.

### A Solution

Compile forge builds for 1.19, so users can play with the current version using forge mod loader.

### Alternatives

N/A

### Anything Else?

Not really, its pretty self explanatory.

**Comment by Tsoccerguy3** [comment]
https://github.com/HexoMod/WorldEditCUI-Forge-Edition This Forge edition may be up gradable to 1.19.4 if you want to reopen this ticket

**Comment by zml2008** [comment]
That project is entirely unrelated to us, and the author has been unwilling to work with our team in the past.
