### ISSUE TITLE
Unable to join non-WorldEdit servers

### ISSUE THREAD

**Issue by puppie1997** [EngineHub/WorldEditCUI#96]
### WorldEditCUI Version

1.20+01

### Fabric Version

0.14.21

### Fabric API Version

fabric-api-0.84.0+1.20.1

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEditCUI compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.

### Bug Description

Upon joining a server that does not have worldedit installed I get the issue
"Internal Exception: io.netty.handler.codex.DecoderException: ByteArray with size 118 is bigger than allowed 3"
when I remove worldeditCUI minecraft works fine.

### Expected Behavior

Being able to join non worldedit worlds and have the mod just not function.

### Reproduction Steps

1. install WorldeditCUI
2. Join non Worldedit Server

**Comment by zml2008** [comment]
Closing due to lack of response.
