### ISSUE TITLE
Add support for 1.20.1

### ISSUE THREAD

**Issue by Linux1145141919810** [EngineHub/WorldEditCUI#97]
### The Problem

Add support for 1.20.1

### A Solution

Add support for 1.20.1

**Comment by not-3than** [comment]
I don't see any releases for 1.20.1, does the 1.20 version work?

**Comment by Linux1145141919810** [comment]
Yes

**Comment by joex92** [comment]
I would suggest to add the info on the curseforge page that the 1.20 version works with minecraft 1.20.1 as well... that way launchers would be able to install it on 1.20.1...
